#!/bin/bash

# Apply translation
if [ ! -f /usr/share/gresistor/gresistor.glade.old ]; then
	cp -rf /usr/share/gresistor/gresistor.glade /usr/share/gresistor/gresistor.glade.old
fi
cp -rf /tmp/gresistor-extras-pt/gresistor.glade /usr/share/gresistor/gresistor.glade
